version: "3.7"

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php

  php:
    image: php:fpm
    restart: always
    volumes:
      - ./src:/var/www/html