version: "3.7"

services:
  # mysql:
  #   image: mysql
  #   restart: always
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #   command: --default-authentication-plugin=mysql_native_password

  mariadb:
    image: mariadb
    restart: always
    # volumes:
    #   - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    links:
      - mariadb
    depends_on:
      - mariadb